[workspace]
authors = ["Fomalhaut647 <fomalhaut@stu.pku.edu.cn>"]
channels = ["conda-forge"]
name = "AIIC-Project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python-dotenv = ">=1.2.2,<2"
